#Expyriment 1.0.0 (Python 3.10.14), .xpe-file, coding: cp1252
#date: Thu Sep 25 2025 21:54:46
#sha1: 787d0b
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Windows', node='LAPTOP-909EKFKU', release='10', version='10.0.26100', machine='AMD64')
Time,Type,Event,Value,Detail,Detail2
664,stderr,received,'Exception ignored in: <function Visual.__del__ at 0x000001B7CF142950>'
664,stderr,received,'Traceback (most recent call last):'
664,stderr,received,'  File "C:\\Users\\USER\\anaconda3\\envs\\machine_learning_general\\lib\\site-packages\\expyriment\\stimuli\\_visual.py", line 266, in __del__'
664,stderr,received,'    if self._compression_filename is not None:'
664,stderr,received,"AttributeError: 'Rectangle' object has no attribute '_compression_filename'"
664,stderr,received,'Traceback (most recent call last):'
664,stderr,received,'  File "C:\\Users\\USER\\OneDrive\\Desktop\\GITHUB\\cogsup-prog\\Assignments\\Week-3\\Exercises\\events\\kazanizsa-square.py", line 15, in <module>'
664,stderr,received,'    rightDown_circle = stimuli.Rectangle(radius=circle_radius, colour=("red"), line_width=1, position=(square_corners[1][0], square_corners[1][1]))'
664,stderr,received,"TypeError: Rectangle.__init__() got an unexpected keyword argument 'radius'"
